service: etl-ocr

plugins:
  - serverless-step-functions
  - serverless-iam-roles-per-function
  - serverless-dotenv-plugin
package:
  exclude:
    - node_modules/**
    - "package.json"
    - "package-lock.json"
  include:
    - ../lambda/**

custom:
  stageName: ${opt:stage, 'dev'}
  region: us-east-2
  mainStateMachineName: ${self:service}-${self:custom.stageName}
  retryMaxAttempts: 36
  retryIntervalSeconds: 300
  retryBackoffRate: 1
  lambdaTimeout: 60
  lambdaMemory: 128

provider:
  name: aws
  region: ${self:custom.region}
  stage: ${self:custom.stageName}
  environment:
    ENV: ${self:custom.stageName}
    REGION: ${self:custom.region}
  stackTags:
    application: ${self:service}
    application-family: etl
    environment: ${self:custom.stageName}

functions:
  ProcessId:
    runtime: nodejs18.x
    handler: lambda/ProcessId/main.handler
    timeout: ${self:custom.lambdaTimeout}
    memorySize: ${self:custom.lambdaMemory}
    iamRoleStatementsName: ${self:service}-${self:custom.stageName}-ProcessId
  GetResultsFromApi:
    runtime: nodejs18.x
    handler: lambda/GetResultsFromApi/main.handler
    timeout: ${self:custom.lambdaTimeout}
    memorySize: ${self:custom.lambdaMemory}
    iamRoleStatementsName: ${self:service}-${self:custom.stageName}-GetResultsFromApi
  QueryFiscalPayload:
    runtime: nodejs18.x
    handler: lambda/QueryFiscalPayload/main.handler
    timeout: ${self:custom.lambdaTimeout}
    memorySize: ${self:custom.lambdaMemory}
    iamRoleStatementsName: ${self:service}-${self:custom.stageName}-QueryFiscalPayload
  SaveRecordToDatabase:
    runtime: nodejs18.x
    handler: lambda/SaveRecordToDatabase/main.handler
    timeout: ${self:custom.lambdaTimeout}
    memorySize: ${self:custom.lambdaMemory}
    iamRoleStatementsName: ${self:service}-${self:custom.stageName}-SaveRecordToDatabase
  SaveImageToS3:
    runtime: nodejs18.x
    handler: lambda/SaveImageToS3/main.handler
    timeout: ${self:custom.lambdaTimeout}
    memorySize: ${self:custom.lambdaMemory}
    iamRoleStatementsName: ${self:service}-${self:custom.stageName}-SaveImageToS3
  GetProvisionalResults:
    runtime: nodejs18.x
    handler: lambda/GetProvisionalResults/main.handler
    timeout: ${self:custom.lambdaTimeout}
    memorySize: ${self:custom.lambdaMemory}
    iamRoleStatementsName: ${self:service}-${self:custom.stageName}-GetProvisionalResults
  DetectTextAwsTextract:
    runtime: nodejs18.x
    handler: lambda/DetectTextAwsTextract/main.handler
    timeout: ${self:custom.lambdaTimeout}
    memorySize: ${self:custom.lambdaMemory}
    iamRoleStatementsName: ${self:service}-${self:custom.stageName}-DetectTextAwsTextract

stepFunctions:
  stateMachines:
    etl-ocr:
      name: ${self:custom.mainStateMachineName}
      definition:
        Comment: This State Machine process images.
        StartAt: ProcessId
        States:
          ProcessId:
            Comment: Procesa y marca como procesado un id desde SQS (FIFO)
            Type: Task
            Resource: !GetAtt ProcessId.Arn
            TimeoutSeconds: ${self:functions.ProcessId.timeout}
            Next: GetResultsFromApi
          GetResultsFromApi:
            Comment: Realiza un GET request hacia el api de resultados para obtener los resultados provisorios
            Type: Task
            Resource: !GetAtt GetResultsFromApi.Arn
            TimeoutSeconds: ${self:functions.GetResultsFromApi.timeout}
            Next: QueryFiscalPayload
          QueryFiscalPayload:
            Comment: Realiza una consulta a DAX (dynamodb) para cargar en memoria la data enviada por el fiscal para la mesa que esta siendo procesada
            Type: Task
            Resource: !GetAtt QueryFiscalPayload.Arn
            TimeoutSeconds: ${self:functions.QueryFiscalPayload.timeout}
            Next: DoWeHaveFiscalData
          DoWeHaveFiscalData:
            Comment: ¿Tenemos data del fiscal recibida?
            Type: Choice
            Choices:
              - Variable: $.fiscalData.isAvailable
                BooleanEquals: true
                Next: IsFiscalDataEqualsToGovermentApiData
              - Variable: $.fiscalData.isAvailable
                BooleanEquals: false
                Next: IsFiscalDataEqualsToGovermentApiData
          IsFiscalDataEqualsToGovermentApiData:
            Comment: ¿Es la data que cargo el fiscal igual a la cargada en API resultados?
            Type: Choice
            Choices:
              - And:
                  - Variable: $.fiscalData.conteoLla
                    NumericEqualsPath: $.govermentData.resultados.lla.votos
                  - Variable: $.fiscalData.conteoUp
                    NumericEqualsPath: $.govermentData.resultados.up.votos
                Next: SaveRecordToDatabase
          SaveRecordToDatabase:
            Comment: Guarda el resultado final del procesamiento de la mesa en db
            Type: Task
            Resource: !GetAtt SaveRecordToDatabase.Arn
            TimeoutSeconds: ${self:functions.SaveRecordToDatabase.timeout}
            Next: Succeed

          # SaveImageToS3:
          #   Comment: Descarga la imagen desde los resultados provisorios y la guarda en S3
          #   Type: Task
          #   Resource: !GetAtt SaveImageToS3.Arn
          #   TimeoutSeconds: ${self:functions.SaveImageToS3.timeout}
          #   Next: GetProvisionalResults
          # DetectTextAwsTextract:
          #   Comment: AWS Textract OCR para extraer los datos desde un telegrama cargado en api provosorios
          #   Type: Task
          #   Resource: !GetAtt DetectTextAwsTextract.Arn
          #   TimeoutSeconds: ${self:functions.DetectTextAwsTextract.timeout}
          #   OutputPath: $.dataFromAwsTextract
          #   Next: Succeed
          Succeed:
            Type: Succeed
